require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TacoTrucksController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # TacoTruck. As you add validations to TacoTruck, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TacoTrucksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all taco_trucks as @taco_trucks" do
      taco_truck = TacoTruck.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:taco_trucks)).to eq([taco_truck])
    end
  end

  describe "GET show" do
    it "assigns the requested taco_truck as @taco_truck" do
      taco_truck = TacoTruck.create! valid_attributes
      get :show, {:id => taco_truck.to_param}, valid_session
      expect(assigns(:taco_truck)).to eq(taco_truck)
    end
  end

  describe "GET new" do
    it "assigns a new taco_truck as @taco_truck" do
      get :new, {}, valid_session
      expect(assigns(:taco_truck)).to be_a_new(TacoTruck)
    end
  end

  describe "GET edit" do
    it "assigns the requested taco_truck as @taco_truck" do
      taco_truck = TacoTruck.create! valid_attributes
      get :edit, {:id => taco_truck.to_param}, valid_session
      expect(assigns(:taco_truck)).to eq(taco_truck)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TacoTruck" do
        expect {
          post :create, {:taco_truck => valid_attributes}, valid_session
        }.to change(TacoTruck, :count).by(1)
      end

      it "assigns a newly created taco_truck as @taco_truck" do
        post :create, {:taco_truck => valid_attributes}, valid_session
        expect(assigns(:taco_truck)).to be_a(TacoTruck)
        expect(assigns(:taco_truck)).to be_persisted
      end

      it "redirects to the created taco_truck" do
        post :create, {:taco_truck => valid_attributes}, valid_session
        expect(response).to redirect_to(TacoTruck.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved taco_truck as @taco_truck" do
        post :create, {:taco_truck => invalid_attributes}, valid_session
        expect(assigns(:taco_truck)).to be_a_new(TacoTruck)
      end

      it "re-renders the 'new' template" do
        post :create, {:taco_truck => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested taco_truck" do
        taco_truck = TacoTruck.create! valid_attributes
        put :update, {:id => taco_truck.to_param, :taco_truck => new_attributes}, valid_session
        taco_truck.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested taco_truck as @taco_truck" do
        taco_truck = TacoTruck.create! valid_attributes
        put :update, {:id => taco_truck.to_param, :taco_truck => valid_attributes}, valid_session
        expect(assigns(:taco_truck)).to eq(taco_truck)
      end

      it "redirects to the taco_truck" do
        taco_truck = TacoTruck.create! valid_attributes
        put :update, {:id => taco_truck.to_param, :taco_truck => valid_attributes}, valid_session
        expect(response).to redirect_to(taco_truck)
      end
    end

    describe "with invalid params" do
      it "assigns the taco_truck as @taco_truck" do
        taco_truck = TacoTruck.create! valid_attributes
        put :update, {:id => taco_truck.to_param, :taco_truck => invalid_attributes}, valid_session
        expect(assigns(:taco_truck)).to eq(taco_truck)
      end

      it "re-renders the 'edit' template" do
        taco_truck = TacoTruck.create! valid_attributes
        put :update, {:id => taco_truck.to_param, :taco_truck => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested taco_truck" do
      taco_truck = TacoTruck.create! valid_attributes
      expect {
        delete :destroy, {:id => taco_truck.to_param}, valid_session
      }.to change(TacoTruck, :count).by(-1)
    end

    it "redirects to the taco_trucks list" do
      taco_truck = TacoTruck.create! valid_attributes
      delete :destroy, {:id => taco_truck.to_param}, valid_session
      expect(response).to redirect_to(taco_trucks_url)
    end
  end

end
